alter type public.dashboard_role add value if not exists 'boss';

create table if not exists public.device_revenue_closings (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices(device_id) on delete cascade,
  closed_at timestamp with time zone not null default now(),
  closed_by uuid default auth.uid(),
  previous_closing_id bigint references public.device_revenue_closings(id) on delete set null,
  previous_closed_at timestamp with time zone,
  coins_in_total numeric not null default 0,
  withdraw_total numeric not null default 0,
  bet_total numeric not null default 0,
  win_total numeric not null default 0,
  house_take_total numeric not null default 0,
  spins_total bigint not null default 0,
  coins_in_delta numeric not null default 0,
  withdraw_delta numeric not null default 0,
  bet_delta numeric not null default 0,
  win_delta numeric not null default 0,
  house_take_delta numeric not null default 0,
  spins_delta bigint not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_device_revenue_closings_device_closed
  on public.device_revenue_closings (device_id, closed_at desc, id desc);

create index if not exists idx_device_revenue_closings_closed_at
  on public.device_revenue_closings (closed_at desc);

create or replace function public.close_device_revenue_period(p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_device_id text := trim(coalesce(p_device_id, ''));
  v_role text := public.current_dashboard_role();
  v_device public.devices%rowtype;
  v_previous public.device_revenue_closings%rowtype;
  v_closing public.device_revenue_closings%rowtype;
  v_prev_coins_in numeric := 0;
  v_prev_withdraw numeric := 0;
  v_prev_bet numeric := 0;
  v_prev_win numeric := 0;
  v_prev_house_take numeric := 0;
  v_prev_spins bigint := 0;
  v_total_coins_in numeric := 0;
  v_total_withdraw numeric := 0;
  v_total_bet numeric := 0;
  v_total_win numeric := 0;
  v_total_house_take numeric := 0;
  v_total_spins bigint := 0;
begin
  if v_role not in ('superadmin', 'admin', 'accounts') then
    raise exception 'Only admin/accounts users can close device accounts';
  end if;

  if v_device_id = '' then
    raise exception 'p_device_id is required';
  end if;

  select *
    into v_device
  from public.devices
  where device_id = v_device_id
  for update;

  if not found then
    raise exception 'device not found: %', v_device_id;
  end if;

  select *
    into v_previous
  from public.device_revenue_closings
  where device_id = v_device_id
  order by closed_at desc, id desc
  limit 1;

  if found then
    v_prev_coins_in := coalesce(v_previous.coins_in_total, 0);
    v_prev_withdraw := coalesce(v_previous.withdraw_total, 0);
    v_prev_bet := coalesce(v_previous.bet_total, 0);
    v_prev_win := coalesce(v_previous.win_total, 0);
    v_prev_house_take := coalesce(v_previous.house_take_total, 0);
    v_prev_spins := coalesce(v_previous.spins_total, 0);
  end if;

  select
    coalesce(sum(s.included_coins_in_amount), 0),
    coalesce(sum(s.included_withdrawal_amount), 0),
    coalesce(sum(s.included_bet_amount), 0),
    coalesce(sum(s.included_win_amount), 0),
    coalesce(sum(s.included_house_take_amount), 0),
    coalesce(sum(s.included_spins_count), 0)::bigint
    into
      v_total_coins_in,
      v_total_withdraw,
      v_total_bet,
      v_total_win,
      v_total_house_take,
      v_total_spins
  from public.device_daily_stats s
  where s.device_id = v_device_id;

  insert into public.device_revenue_closings (
    device_id,
    closed_by,
    previous_closing_id,
    previous_closed_at,
    coins_in_total,
    withdraw_total,
    bet_total,
    win_total,
    house_take_total,
    spins_total,
    coins_in_delta,
    withdraw_delta,
    bet_delta,
    win_delta,
    house_take_delta,
    spins_delta,
    metadata
  )
  values (
    v_device_id,
    auth.uid(),
    case when v_previous.id is null then null else v_previous.id end,
    v_previous.closed_at,
    greatest(v_total_coins_in, 0),
    greatest(v_total_withdraw, 0),
    greatest(v_total_bet, 0),
    greatest(v_total_win, 0),
    greatest(v_total_house_take, 0),
    greatest(v_total_spins, 0),
    greatest(v_total_coins_in - v_prev_coins_in, 0),
    greatest(v_total_withdraw - v_prev_withdraw, 0),
    greatest(v_total_bet - v_prev_bet, 0),
    greatest(v_total_win - v_prev_win, 0),
    greatest(v_total_house_take - v_prev_house_take, 0),
    greatest(v_total_spins - v_prev_spins, 0),
    jsonb_build_object(
      'source', 'dashboard_device_close_accounts',
      'deviceName', v_device.name,
      'deploymentMode', v_device.deployment_mode
    )
  )
  returning * into v_closing;

  return jsonb_build_object(
    'ok', true,
    'id', v_closing.id,
    'device_id', v_closing.device_id,
    'closed_at', v_closing.closed_at,
    'coins_in', v_closing.coins_in_delta,
    'withdrawal', v_closing.withdraw_delta,
    'income', v_closing.coins_in_delta - v_closing.withdraw_delta,
    'bet', v_closing.bet_delta,
    'win', v_closing.win_delta,
    'house_take', v_closing.house_take_delta,
    'spins', v_closing.spins_delta
  );
end;
$$;

create or replace view public.boss_revenue_daily as
with closed_rows as (
  select
    (c.closed_at at time zone 'Asia/Manila')::date as report_date,
    coalesce(c.coins_in_delta, 0) as coins_in,
    coalesce(c.withdraw_delta, 0) as withdrawal,
    coalesce(c.bet_delta, 0) as bet,
    coalesce(c.win_delta, 0) as win,
    coalesce(c.house_take_delta, 0) as house_take,
    coalesce(c.spins_delta, 0) as spins
  from public.device_revenue_closings c
),
latest_closing as (
  select distinct on (c.device_id)
    c.device_id,
    c.coins_in_total,
    c.withdraw_total,
    c.bet_total,
    c.win_total,
    c.house_take_total,
    c.spins_total
  from public.device_revenue_closings c
  order by c.device_id, c.closed_at desc, c.id desc
),
eligible_totals as (
  select
    s.device_id,
    coalesce(sum(s.included_coins_in_amount), 0) as coins_in_total,
    coalesce(sum(s.included_withdrawal_amount), 0) as withdraw_total,
    coalesce(sum(s.included_bet_amount), 0) as bet_total,
    coalesce(sum(s.included_win_amount), 0) as win_total,
    coalesce(sum(s.included_house_take_amount), 0) as house_take_total,
    coalesce(sum(s.included_spins_count), 0)::bigint as spins_total
  from public.device_daily_stats s
  group by s.device_id
),
open_rows as (
  select
    (now() at time zone 'Asia/Manila')::date as report_date,
    greatest(coalesce(t.coins_in_total, 0) - coalesce(l.coins_in_total, 0), 0) as coins_in,
    greatest(coalesce(t.withdraw_total, 0) - coalesce(l.withdraw_total, 0), 0) as withdrawal,
    greatest(coalesce(t.bet_total, 0) - coalesce(l.bet_total, 0), 0) as bet,
    greatest(coalesce(t.win_total, 0) - coalesce(l.win_total, 0), 0) as win,
    greatest(coalesce(t.house_take_total, 0) - coalesce(l.house_take_total, 0), 0) as house_take,
    greatest(coalesce(t.spins_total, 0) - coalesce(l.spins_total, 0), 0) as spins
  from public.devices d
  left join latest_closing l on l.device_id = d.device_id
  left join eligible_totals t on t.device_id = d.device_id
),
all_rows as (
  select * from closed_rows
  union all
  select * from open_rows
)
select
  report_date,
  sum(coins_in) as coins_in,
  sum(withdrawal) as withdrawal,
  sum(coins_in - withdrawal) as income,
  sum(bet) as bet,
  sum(win) as win,
  sum(house_take) as house_take,
  sum(spins) as spins
from all_rows
group by report_date
having
  sum(coins_in) <> 0
  or sum(withdrawal) <> 0
  or sum(bet) <> 0
  or sum(win) <> 0
  or sum(house_take) <> 0
  or sum(spins) <> 0;

alter table public.device_revenue_closings owner to postgres;
alter function public.close_device_revenue_period(text) owner to postgres;
alter view public.boss_revenue_daily owner to postgres;

grant all on table public.device_revenue_closings to anon;
grant all on table public.device_revenue_closings to authenticated;
grant all on table public.device_revenue_closings to service_role;

grant all on sequence public.device_revenue_closings_id_seq to anon;
grant all on sequence public.device_revenue_closings_id_seq to authenticated;
grant all on sequence public.device_revenue_closings_id_seq to service_role;

grant all on function public.close_device_revenue_period(text) to anon;
grant all on function public.close_device_revenue_period(text) to authenticated;
grant all on function public.close_device_revenue_period(text) to service_role;

grant all on table public.boss_revenue_daily to anon;
grant all on table public.boss_revenue_daily to authenticated;
grant all on table public.boss_revenue_daily to service_role;
